version: "3.7"

services:
  forta:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        buildno: 1
    environment:
      - TZ=Europe/Kiev
      - FORTA_PASSPHRASE=$FORTA_PASSPHRASE
      - FORTA_DIR=/keys
    volumes:
      - "/keys:/root/.forta/.keys"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always